In [14]:
import numpy as np
import scipy
from scipy.spatial.distance import cdist
from numpy.linalg import norm

In [4]:
norm(np.array([-1, 2, -1]), ord=1)

4

In [5]:
np.dot([1, 2, 3], [-3, 1, 1])

2

In [6]:
np.arange(1, 2, 0.3, dtype=float)

array([ 1. ,  1.3,  1.6,  1.9])

In [7]:
np.array(1, 2, 3, 4, 5, dtype=float)

ValueError: only 2 non-keyword arguments accepted

In [8]:
 np.array([False, False, True])

array([False, False,  True], dtype=bool)

In [9]:
np.array([1, 2, 3, 4, 5], dtype=float)

array([ 1.,  2.,  3.,  4.,  5.])

In [10]:
a = np.array([6, 3, -5])
b = np.array([-1, 0, 7])
cdist(a[:, np.newaxis], b[:, np.newaxis], metric='euclidean')

array([[  7.,   6.,   1.],
       [  4.,   3.,   4.],
       [  4.,   5.,  12.]])

In [11]:
np.linalg.norm(a, ord=2) - np.linalg.norm(b, ord=2)

1.2955324534752801

In [12]:
cdist(b, a, metric='euclidean')

ValueError: XA must be a 2-dimensional array.

In [15]:
scipy.spatial.distance.cdist(a[np.newaxis, :], b[np.newaxis, :], metric='euclidean')

array([[ 14.2126704]])

In [16]:
cdist(a, b, metric='euclidean')

ValueError: XA must be a 2-dimensional array.

In [17]:
np.linalg.norm(a -b, ord=2)

14.212670403551895

In [31]:
a = np.array([0, -1, 11])
b = np.array([3, 7, 2])
a.dot(b)

15

In [32]:
np.dot(a, b)

15

In [33]:
a * b

array([ 0, -7, 22])

In [34]:
np.dot(a, b) / np.linalg.norm(a) / np.linalg.norm(b)

0.17247076868185271

In [35]:
a = np.array([8, 10, -1, 0, 0])

In [38]:
 a.reshape((1, 5)).shape

(1, 5)

In [40]:
a[np.newaxis, :].shape

(1, 5)

In [42]:
a[:, np.newaxis].shape

(5, 1)